// <auto-generated />
namespace CafeApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingbridgingtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingbridgingtable));
        
        string IMigrationMetadata.Id
        {
            get { return "202106091828522_adding-bridging-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
